#!/usr/bin/env node
/**
 * The install-time opt-in.
 *
 * `@ishan/ecosystem-auth` is a heavy sidecar - Better Auth, Kysely and a
 * Postgres driver - and most surfaces do not need accounts yet. So the choice
 * is made at install time, not at runtime.
 *
 * This matters because a runtime flag cannot do it. If any reachable code path
 * imports the package, Vite and SvelteKit resolve it at build time, so a surface
 * that "disabled" auth at runtime would still have it in `node_modules` and in
 * its bundle. Generating the file is what actually keeps the dependency out.
 *
 * What it writes, in the surface:
 *
 *   src/lib/server/auth-provider.ts   the single file that imports the sidecar
 *
 * That file is the seam. Swapping identity providers later means swapping this
 * one file, and nothing else in the surface knows which engine is behind it -
 * `resolveRole`, `hasPremiumAccess` and `hasPermission` all live in the
 * dependency-free core and keep working.
 *
 * It deliberately does NOT touch `hooks.server.ts`: that file is usually already
 * doing real work, and clobbering it would be the kind of silent damage this
 * script exists to avoid. It prints the snippet instead.
 *
 * Usage:
 *   node scripts/scaffold.mjs --surface ../technical-authority-website
 *   node scripts/scaffold.mjs --surface ../foo --dry-run
 *   node scripts/scaffold.mjs --surface ../foo --force
 *
 * Exit code 1 on a usage error or a refused overwrite.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = fileURLToPath(new URL('..', import.meta.url));

function parseArgs(argv) {
	const args = { surface: null, dryRun: false, force: false, schema: 'auth', driver: 'pg' };
	for (let i = 0; i < argv.length; i++) {
		const arg = argv[i];
		if (arg === '--surface' || arg === '-s') args.surface = argv[++i];
		else if (arg === '--schema') args.schema = argv[++i];
		else if (arg === '--driver') args.driver = argv[++i];
		else if (arg === '--dry-run') args.dryRun = true;
		else if (arg === '--force') args.force = true;
		else if (arg === '--help' || arg === '-h') args.help = true;
		else {
			console.error(`Unknown argument: ${arg}`);
			process.exit(1);
		}
	}
	return args;
}

function usage() {
	console.log(`Usage: node scripts/scaffold.mjs --surface <path> [options]

  --surface, -s <path>   The consuming surface repository. Required.
  --schema <name>        Postgres schema for the identity tables. Default: auth
  --driver <pg|postgres> Postgres driver for the pool. Default: pg
  --dry-run              Report what would change without writing.
  --force                Overwrite an existing auth-provider.ts.
`);
}

function providerSource({ schema, driver, surfaceName }) {
	const driverImport =
		driver === 'postgres'
			? `import postgres from 'postgres';\nimport { PostgresJSDialect } from 'kysely-postgres-js';`
			: `import { Pool } from 'pg';\nimport { PostgresDialect } from 'kysely';`;

	// Built as a whole block rather than interpolated onto a partial line, so the
	// generated file has consistent indentation. This code gets committed.
	const databaseBlock =
		driver === 'postgres'
			? `{
			dialect: new PostgresJSDialect({
				postgres: postgres(connectionString, {
					// Supabase's Supavisor pooler runs in transaction mode, where
					// server-side prepared statements are not available.
					prepare: false,
					max: 1,
				}),
			}),
			type: 'postgres',
			schemaName: '${schema}',
		}`
			: `{
			dialect: new PostgresDialect({
				pool: new Pool({
					connectionString,
					// Small on purpose: Hyperdrive owns the real pool, and a
					// Worker can only open six outbound connections per invocation.
					max: 1,
				}),
			}),
			type: 'postgres',
			schemaName: '${schema}',
		}`;

	return `/**
 * Auth provider - the single install-time seam for identity in ${surfaceName}.
 *
 * Generated by \`@ishan/ecosystem-auth\`'s \`scripts/scaffold.mjs\`. This is the
 * only file in the surface that imports the auth sidecar, so removing it is all
 * it takes to opt back out.
 *
 * Configuration is passed in rather than read here. Cloudflare bindings live on
 * \`platform.env\` and differ between requests, so reading env at module scope
 * would break the moment a second environment existed.
 *
 * Two non-obvious requirements, both verified against Better Auth 1.7.x:
 *
 *   1. \`database\` must be the object form. A bare connection string throws
 *      \`TypeError: Cannot use 'in' operator\` from an internal init call, which
 *      surfaces as an unhandled rejection the caller cannot catch.
 *   2. \`schemaName\` is only supported on the \`{ dialect }\` / \`{ db }\` forms.
 *      Keeping the tables in a dedicated schema means PostgREST - which exposes
 *      \`public\` only - cannot reach them.
 *
 * The runtime also needs \`nodejs_compat\` in wrangler.toml: Better Auth's
 * password hashing uses native \`node:crypto\` scrypt, and without that flag it
 * falls back to a pure-JS implementation that intermittently exceeds the
 * Workers CPU budget on sign-up.
 */

${driverImport}
import { createAuthAdapter, type AuthAdapter } from '@ishan/ecosystem-auth';

export interface AuthProviderConfig {
	/** Postgres connection string - on Workers, the Hyperdrive binding's. */
	connectionString: string;
	/** Signing secret for sessions and tokens. */
	secret: string;
	/** Absolute origin this surface is served from. */
	baseURL: string;
	/** Extra origins allowed to post credentials. */
	trustedOrigins?: readonly string[];
}

export function createAuth(config: AuthProviderConfig): AuthAdapter {
	return createAuthAdapter({
		database: ${databaseBlock},
		secret: config.secret,
		baseURL: config.baseURL,
		...(config.trustedOrigins ? { trustedOrigins: config.trustedOrigins } : {}),
	});
}
`;
}

const HOOK_SNIPPET = `// hooks.server.ts - add to the existing handle, do not replace it.
import { svelteKitHandler } from 'better-auth/svelte-kit';
import { building } from '$app/environment';
import { createAuth } from '$lib/server/auth-provider';

// Build it per request: the Hyperdrive binding lives on platform.env.
const adapter = createAuth({
	connectionString: platform.env.HYPERDRIVE.connectionString,
	secret: platform.env.BETTER_AUTH_SECRET,
	baseURL: platform.env.PUBLIC_SITE_URL,
});

return svelteKitHandler({ event, resolve, auth: adapter.auth, building });`;

const args = parseArgs(process.argv.slice(2));

if (args.help) {
	usage();
	process.exit(0);
}

if (!args.surface) {
	console.error('--surface is required.\n');
	usage();
	process.exit(1);
}

const target = resolve(HERE, args.surface);
const name = target.split('/').filter(Boolean).pop() ?? 'surface';

/**
 * SvelteKit is configured one of two ways, and both are in use here: the classic
 * `svelte.config.js`, or the newer `sveltekit({ adapter })` call inside
 * `vite.config.ts` - which is what technical-authority-website does. Checking
 * only for the first rejected a working project, so check both.
 */
function looksLikeSvelteKit(dir) {
	for (const file of ['svelte.config.js', 'svelte.config.ts', 'svelte.config.mjs']) {
		if (existsSync(join(dir, file))) return true;
	}
	for (const file of ['vite.config.ts', 'vite.config.js', 'vite.config.mts']) {
		const path = join(dir, file);
		if (!existsSync(path)) continue;
		if (/@sveltejs\/kit\/vite|sveltekit\s*\(/.test(readFileSync(path, 'utf8'))) return true;
	}
	return false;
}

if (!existsSync(target)) {
	console.error(`✘ Surface not found: ${target}`);
	process.exit(1);
}
if (!looksLikeSvelteKit(target)) {
	console.error(
		`✘ ${target} does not look like a SvelteKit project ` +
			'(no svelte.config.js, and no sveltekit() call in vite.config.ts).',
	);
	process.exit(1);
}

const providerPath = join(target, 'src/lib/server/auth-provider.ts');
const exists = existsSync(providerPath);

if (exists && !args.force) {
	const current = readFileSync(providerPath, 'utf8');
	if (current.includes('createAuthAdapter')) {
		console.log(`✔ ${name} already has an auth provider. Nothing to do.`);
		console.log(`  Use --force to regenerate it.`);
		process.exit(0);
	}
	console.error(`✘ ${providerPath} exists and was not generated by this scaffold.`);
	console.error('  Refusing to overwrite. Re-run with --force if you are sure.');
	process.exit(1);
}

const source = providerSource({ schema: args.schema, driver: args.driver, surfaceName: name });

if (args.dryRun) {
	console.log(`Would write ${providerPath}:`);
	console.log('─'.repeat(72));
	console.log(source);
	console.log('─'.repeat(72));
	process.exit(0);
}

mkdirSync(dirname(providerPath), { recursive: true });
writeFileSync(providerPath, source, 'utf8');

const deps =
	args.driver === 'postgres'
		? 'npm i @ishan/ecosystem-auth postgres kysely-postgres-js'
		: 'npm i @ishan/ecosystem-auth pg && npm i -D @types/pg';

console.log(`✔ Wrote ${providerPath}`);
console.log(`
Next steps for ${name}:

  1. Install the sidecar (this is the actual opt-in):
       ${deps}

  2. Generate the Better Auth tables into the '${args.schema}' schema:
       npx auth@latest migrate

  3. Add nodejs_compat to wrangler.toml - without it, sign-up can exceed the
     Workers CPU budget:
       compatibility_flags = ["nodejs_compat"]

  4. Wire the hook. Add to your existing handle in src/hooks.server.ts:

${HOOK_SNIPPET.split('\n')
	.map((line) => '     ' + line)
	.join('\n')}

  5. Verify: npm run check
`);
